title: Naresh
# logo : img/1000067738.jpg
description: ğŸ“Š Driven junior Data Scientist and recent B.Sc. graduate with a robust background in Computer Science. Fueled by a passion for data science and analytics, I excel in self-directed learning and swiftly adapt to new challenges.

ğŸ” Actively seeking dynamic roles to apply my technical prowess and analytical skills. Dedicated to uncovering actionable insights and delivering impactful solutions through adept data manipulation, machine learning, and visualization techniques.
show_downloads: True
theme: jekyll-theme-minimal
